DROP table IF EXISTS data_9.final_series; 
create table data_9.final_series AS

with chart as 
(
	select
		stay_id as stay_id_chart,
		date as date_chart,
		"avg SaO2",
		"min SaO2",
		"max SaO2",
		"first SaO2",
		"last SaO2",
		"avg Respiration",
		"min Respiration",
		"max Respiration",
		"first Respiration",
		"last Respiration",
		"avg Heart Rate",
		"min Heart Rate",
		"max Heart Rate",
		"first Heart Rate",
		"last Heart Rate",
		"avg Systemic Systolic",
		"min Systemic Systolic",
		"max Systemic Systolic",
		"first Systemic Systolic",
		"last Systemic Systolic",
		"avg Systemic Diastolic",
		"min Systemic Diastolic",
		"max Systemic Diastolic",
		"first Systemic Diastolic",
		"last Systemic Diastolic",
		"avg Systemic Mean",
		"min Systemic Mean",
		"max Systemic Mean",
		"first Systemic Mean",
		"last Systemic Mean",
		"avg Compliance",
		"min Compliance",
		"max Compliance",
		"first Compliance",
		"last Compliance",
		"avg FiO2",
		"min FiO2",
		"max FiO2",
		"first FiO2",
		"last FiO2",
		"avg Minute Ventilation",
		"min Minute Ventilation",
		"max Minute Ventilation",
		"first Minute Ventilation",
		"last Minute Ventilation",
		"avg Mean Airway Pressure",
		"min Mean Airway Pressure",
		"max Mean Airway Pressure",
		"first Mean Airway Pressure",
		"last Mean Airway Pressure",
		"avg Peak Airway Pressure",
		"min Peak Airway Pressure",
		"max Peak Airway Pressure",
		"first Peak Airway Pressure",
		"last Peak Airway Pressure",
		"avg PEEP",
		"min PEEP",
		"max PEEP",
		"first PEEP",
		"last PEEP",
		"avg PC mode",
		"min PC mode",
		"max PC mode",
		"first PC mode",
		"last PC mode",
		"avg Pressure Support",
		"min Pressure Support",
		"max Pressure Support",
		"first Pressure Support",
		"last Pressure Support",
		"avg Plateau",
		"min Plateau",
		"max Plateau",
		"first Plateau",
		"last Plateau",
		"avg Tidal Volume",
		"min Tidal Volume",
		"max Tidal Volume",
		"first Tidal Volume",
		"last Tidal Volume",
		"avg Respiratory Rate",
		"min Respiratory Rate",
		"max Respiratory Rate",
		"first Respiratory Rate",
		"last Respiratory Rate",
		"avg ROXindex",
		"min ROXindex",
		"max ROXindex",
		"first ROXindex",
		"last ROXindex",
		"avg Daily RSBI",
		"min Daily RSBI",
		"max Daily RSBI",
		"first Daily RSBI",
		"last Daily RSBI",
		"avg Unable RSBI",
		"min Unable RSBI",
		"max Unable RSBI",
		"first Unable RSBI",
		"last Unable RSBI",
		"avg RASS",
		"min RASS",
		"max RASS",
		"first RASS",
		"last RASS"
	FROM
		data_9.chart
)

, lab_without_stayid as 
(
	SELECT
		subject_id,
		date as date_lab,
		"avg Platelets x1000",
		"min Platelets x1000",
		"max Platelets x1000",
		"first Platelets x1000",
		"last Platelets x1000",
		"avg WBC x1000",
		"min WBC x1000",
		"max WBC x1000",
		"first WBC x1000",
		"last WBC x1000",
		"avg Hgb",
		"min Hgb",
		"max Hgb",
		"first Hgb",
		"last Hgb",
		"avg Albumin",
		"min Albumin",
		"max Albumin",
		"first Albumin",
		"last Albumin",
		"avg Total Protein",
		"min Total Protein",
		"max Total Protein",
		"first Total Protein",
		"last Total Protein",
		"avg Total Bilirubin",
		"min Total Bilirubin",
		"max Total Bilirubin",
		"first Total Bilirubin",
		"last Total Bilirubin",
		"avg PO2",
		"min PO2",
		"max PO2",
		"first PO2",
		"last PO2",
		"avg PaCO2",
		"min PaCO2",
		"max PaCO2",
		"first PaCO2",
		"last PaCO2",
		"avg Glucose",
		"min Glucose",
		"max Glucose",
		"first Glucose",
		"last Glucose",
		"avg BUN",
		"min BUN",
		"max BUN",
		"first BUN",
		"last BUN",
		"avg pH",
		"min pH",
		"max pH",
		"first pH",
		"last pH",
		"avg Sodium",
		"min Sodium",
		"max Sodium",
		"first Sodium",
		"last Sodium",
		"avg Potassium",
		"min Potassium",
		"max Potassium",
		"first Potassium",
		"last Potassium",
		"avg Magnesium",
		"min Magnesium",
		"max Magnesium",
		"first Magnesium",
		"last Magnesium",
		"avg Calcium",
		"min Calcium",
		"max Calcium",
		"first Calcium",
		"last Calcium",
		"avg Chloride",
		"min Chloride",
		"max Chloride",
		"first Chloride",
		"last Chloride",
		"avg creatinine",
		"min creatinine",
		"max creatinine",
		"first creatinine",
		"last creatinine",
		"avg HCO3",
		"min HCO3",
		"max HCO3",
		"first HCO3",
		"last HCO3",
		"avg Phosphate",
		"min Phosphate",
		"max Phosphate",
		"first Phosphate",
		"last Phosphate",
		"avg Alkaline Phos.",
		"min Alkaline Phos.",
		"max Alkaline Phos.",
		"first Alkaline Phos.",
		"last Alkaline Phos.",
		"avg AST (SGOT)",
		"min AST (SGOT)",
		"max AST (SGOT)",
		"first AST (SGOT)",
		"last AST (SGOT)",
		"avg ALT (SGPT)",
		"min ALT (SGPT)",
		"max ALT (SGPT)",
		"first ALT (SGPT)",
		"last ALT (SGPT)",
		"avg PT-INR",
		"min PT-INR",
		"max PT-INR",
		"first PT-INR",
		"last PT-INR"
	FROM 
		data_9.lab_timeseries as lab
)
, lab AS
(
	SELECT 
		--l.subject_id,
		stay_id as stay_id_lab,
		date_lab,
		"avg Platelets x1000",
		"min Platelets x1000",
		"max Platelets x1000",
		"first Platelets x1000",
		"last Platelets x1000",
		"avg WBC x1000",
		"min WBC x1000",
		"max WBC x1000",
		"first WBC x1000",
		"last WBC x1000",
		"avg Hgb",
		"min Hgb",
		"max Hgb",
		"first Hgb",
		"last Hgb",
		"avg Albumin",
		"min Albumin",
		"max Albumin",
		"first Albumin",
		"last Albumin",
		"avg Total Protein",
		"min Total Protein",
		"max Total Protein",
		"first Total Protein",
		"last Total Protein",
		"avg Total Bilirubin",
		"min Total Bilirubin",
		"max Total Bilirubin",
		"first Total Bilirubin",
		"last Total Bilirubin",
		"avg PO2",
		"min PO2",
		"max PO2",
		"first PO2",
		"last PO2",
		"avg PaCO2",
		"min PaCO2",
		"max PaCO2",
		"first PaCO2",
		"last PaCO2",
		"avg Glucose",
		"min Glucose",
		"max Glucose",
		"first Glucose",
		"last Glucose",
		"avg BUN",
		"min BUN",
		"max BUN",
		"first BUN",
		"last BUN",
		"avg pH",
		"min pH",
		"max pH",
		"first pH",
		"last pH",
		"avg Sodium",
		"min Sodium",
		"max Sodium",
		"first Sodium",
		"last Sodium",
		"avg Potassium",
		"min Potassium",
		"max Potassium",
		"first Potassium",
		"last Potassium",
		"avg Magnesium",
		"min Magnesium",
		"max Magnesium",
		"first Magnesium",
		"last Magnesium",
		"avg Calcium",
		"min Calcium",
		"max Calcium",
		"first Calcium",
		"last Calcium",
		"avg Chloride",
		"min Chloride",
		"max Chloride",
		"first Chloride",
		"last Chloride",
		"avg creatinine",
		"min creatinine",
		"max creatinine",
		"first creatinine",
		"last creatinine",
		"avg HCO3",
		"min HCO3",
		"max HCO3",
		"first HCO3",
		"last HCO3",
		"avg Phosphate",
		"min Phosphate",
		"max Phosphate",
		"first Phosphate",
		"last Phosphate",
		"avg Alkaline Phos.",
		"min Alkaline Phos.",
		"max Alkaline Phos.",
		"first Alkaline Phos.",
		"last Alkaline Phos.",
		"avg AST (SGOT)",
		"min AST (SGOT)",
		"max AST (SGOT)",
		"first AST (SGOT)",
		"last AST (SGOT)",
		"avg ALT (SGPT)",
		"min ALT (SGPT)",
		"max ALT (SGPT)",
		"first ALT (SGPT)",
		"last ALT (SGPT)",
		"avg PT-INR",
		"min PT-INR",
		"max PT-INR",
		"first PT-INR",
		"last PT-INR"

	FROM
		lab_without_stayid as lab
	LEFT JOIN data_9.icu_detail as detail
	on lab.subject_id = detail.subject_id and lab.date_lab>= to_date(detail.icu_intime::text, 'yyyy-mm-dd') and lab.date_lab <=to_date(detail.icu_outtime::text, 'yyyy-mm-dd')
)

, ingredient AS
(
	SELECT 
		stay_id as stay_id_ingredient,
		to_date(year || '-' || month || '-' || date, 'YYYY-MM-DD') AS date_ingredient,
		"Vasopressor",
		"Relaxant",
		"Sedation",
		"PPI",
		"Pain control"
	FROM data_9.ingredientevents_select --03  //stay 分開
)
, intakeoutput AS
(
	SELECT
		stay_id as stay_id_intakeoutput,
		date as date_intakeoutput,
		total,
		total2
	FROM
		data_9.intakeoutput_date
)

, intakeoutput_new AS
(
	SELECT
		stay_id as stay_id_intakeoutput_new,
		date as date_intakeoutput_new,
		"Fluid_intake_value",
		"Nutrition_Enteral_value",
		"Urine_value"
	FROM
		data_9.intakeoutput_new
)
, micro AS 
(
	SELECT
		--micro.subject_id,
		stay_id as stay_id_micro,
		chartdate as date_micro,
		"Aspergillus",
		"Candida",
		--"GPB",
		--"GNB",
		--"Fungi"
		"Abdomen",
		"Blood",
		"Respiratory tract",
		"Skin and soft tissue",
		"Urinary tract",
		"Others"
		--"GPB",
		--"GNB",
		--"Fungi"
	FROM
		data_9.micro_new as micro
	LEFT JOIN 
		data_9.icu_detail as detail
	on micro.subject_id = detail.subject_id and micro.chartdate>= to_date(detail.icu_intime::text, 'yyyy-mm-dd') and micro.chartdate <=to_date(detail.icu_outtime::text, 'yyyy-mm-dd')
)
, dod as 
(
	SELECT
		stay_id as stay_id_dod,
		case when dod is not null then dod else null end as date_dod,  
		case when dod is not null then 1 else 0 end as dod
	FROM
		data_9.icu_detail
	WHERE 
		dod is not null
)
, pcmode as 
(
	SELECT
		stay_id as stay_id_pc,
		date as date_pc,
		"PC_mode"
	FROM
		data_9.pcmode
)
, final as
(
	SELECT
		* 
	FROM 
		chart
	FULL JOIN 
		lab
	ON chart.stay_id_chart = lab.stay_id_lab and chart.date_chart = lab.date_lab
	
	FULL JOIN
		ingredient
	ON lab.stay_id_lab = ingredient.stay_id_ingredient and lab.date_lab = ingredient.date_ingredient

	FULL JOIN
		intakeoutput
	ON ingredient.stay_id_ingredient = intakeoutput.stay_id_intakeoutput and ingredient.date_ingredient = intakeoutput.date_intakeoutput

	FULL JOIN
		micro
	ON intakeoutput.stay_id_intakeoutput = micro.stay_id_micro and intakeoutput.date_intakeoutput = micro.date_micro
	
	FULL JOIN
		pcmode
	ON micro.stay_id_micro = pcmode.stay_id_pc and  micro.date_micro = pcmode.date_pc
	
	FULL JOIN --20230627
		intakeoutput_new
	ON pcmode.stay_id_pc = intakeoutput_new.stay_id_intakeoutput_new and pcmode.date_pc = intakeoutput_new.date_intakeoutput_new
)

,final2 as 
(
	SELECT 
		COALESCE(stay_id_chart,stay_id_lab,stay_id_ingredient,stay_id_intakeoutput,stay_id_micro,stay_id_pc,stay_id_intakeoutput_new) as stay_id,
		COALESCE(date_chart,date_lab,date_ingredient,date_intakeoutput,date_micro,date_pc,date_intakeoutput_new) as date,
	--------------------
		"avg SaO2",
		"min SaO2",
		"max SaO2",
		"first SaO2",
		"last SaO2",
		"avg Respiration",
		"min Respiration",
		"max Respiration",
		"first Respiration",
		"last Respiration",
		"avg Heart Rate",
		"min Heart Rate",
		"max Heart Rate",
		"first Heart Rate",
		"last Heart Rate",
		"avg Systemic Systolic",
		"min Systemic Systolic",
		"max Systemic Systolic",
		"first Systemic Systolic",
		"last Systemic Systolic",
		"avg Systemic Diastolic",
		"min Systemic Diastolic",
		"max Systemic Diastolic",
		"first Systemic Diastolic",
		"last Systemic Diastolic",
		"avg Systemic Mean",
		"min Systemic Mean",
		"max Systemic Mean",
		"first Systemic Mean",
		"last Systemic Mean",
		"avg Compliance",
		"min Compliance",
		"max Compliance",
		"first Compliance",
		"last Compliance",
		"avg FiO2",
		"min FiO2",
		"max FiO2",
		"first FiO2",
		"last FiO2",
		"avg Minute Ventilation",
		"min Minute Ventilation",
		"max Minute Ventilation",
		"first Minute Ventilation",
		"last Minute Ventilation",
		"avg Mean Airway Pressure",
		"min Mean Airway Pressure",
		"max Mean Airway Pressure",
		"first Mean Airway Pressure",
		"last Mean Airway Pressure",
		"avg Peak Airway Pressure",
		"min Peak Airway Pressure",
		"max Peak Airway Pressure",
		"first Peak Airway Pressure",
		"last Peak Airway Pressure",
		"avg PEEP",
		"min PEEP",
		"max PEEP",
		"first PEEP",
		"last PEEP",
		--"avg PC mode",
		case when "avg PEEP" is not null and "avg FiO2" is not null and "PC_mode" is null then 'AC' else 'PC_mode' end as "avg PC mode",		
		"min PC mode",
		"max PC mode",
		"first PC mode",
		"last PC mode",
		"avg Pressure Support",
		"min Pressure Support",
		"max Pressure Support",
		"first Pressure Support",
		"last Pressure Support",
		"avg Plateau",
		"min Plateau",
		"max Plateau",
		"first Plateau",
		"last Plateau",
		"avg Tidal Volume",
		"min Tidal Volume",
		"max Tidal Volume",
		"first Tidal Volume",
		"last Tidal Volume",
		"avg Respiratory Rate",
		"min Respiratory Rate",
		"max Respiratory Rate",
		"first Respiratory Rate",
		"last Respiratory Rate",
		"avg ROXindex",
		"min ROXindex",
		"max ROXindex",
		"first ROXindex",
		"last ROXindex",
		--"avg Daily RSBI",
		case when "avg Daily RSBI" = 1 then 1 else 0 end as "Daily RSBI",
		--"min Daily RSBI",
		--"max Daily RSBI",
		--"first Daily RSBI",
		--"last Daily RSBI",
		--"avg Unable RSBI",
		case when "avg Unable RSBI" = 1 then 1 else 0 end as "Unable RSBI",
		--"min Unable RSBI",
		--"max Unable RSBI",
		--"first Unable RSBI",
		--"last Unable RSBI",
		"avg RASS",
		"min RASS",
		"max RASS",
		"first RASS",
		"last RASS",
	-------------------------------------
		"avg Platelets x1000",
		"min Platelets x1000",
		"max Platelets x1000",
		"first Platelets x1000",
		"last Platelets x1000",
		"avg WBC x1000",
		"min WBC x1000",
		"max WBC x1000",
		"first WBC x1000",
		"last WBC x1000",
		"avg Hgb",
		"min Hgb",
		"max Hgb",
		"first Hgb",
		"last Hgb",
		"avg Albumin",
		"min Albumin",
		"max Albumin",
		"first Albumin",
		"last Albumin",
		"avg Total Protein",
		"min Total Protein",
		"max Total Protein",
		"first Total Protein",
		"last Total Protein",
		"avg Total Bilirubin",
		"min Total Bilirubin",
		"max Total Bilirubin",
		"first Total Bilirubin",
		"last Total Bilirubin",
		"avg PO2",
		"min PO2",
		"max PO2",
		"first PO2",
		"last PO2",
		"avg PaCO2",
		"min PaCO2",
		"max PaCO2",
		"first PaCO2",
		"last PaCO2",
		"avg Glucose",
		"min Glucose",
		"max Glucose",
		"first Glucose",
		"last Glucose",
		"avg BUN",
		"min BUN",
		"max BUN",
		"first BUN",
		"last BUN",
		"avg pH",
		"min pH",
		"max pH",
		"first pH",
		"last pH",
		"avg Sodium",
		"min Sodium",
		"max Sodium",
		"first Sodium",
		"last Sodium",
		"avg Potassium",
		"min Potassium",
		"max Potassium",
		"first Potassium",
		"last Potassium",
		"avg Magnesium",
		"min Magnesium",
		"max Magnesium",
		"first Magnesium",
		"last Magnesium",
		"avg Calcium",
		"min Calcium",
		"max Calcium",
		"first Calcium",
		"last Calcium",
		"avg Chloride",
		"min Chloride",
		"max Chloride",
		"first Chloride",
		"last Chloride",
		"avg creatinine",
		"min creatinine",
		"max creatinine",
		"first creatinine",
		"last creatinine",
		"avg HCO3",
		"min HCO3",
		"max HCO3",
		"first HCO3",
		"last HCO3",
		"avg Phosphate",
		"min Phosphate",
		"max Phosphate",
		"first Phosphate",
		"last Phosphate",
		"avg Alkaline Phos.",
		"min Alkaline Phos.",
		"max Alkaline Phos.",
		"first Alkaline Phos.",
		"last Alkaline Phos.",
		"avg AST (SGOT)",
		"min AST (SGOT)",
		"max AST (SGOT)",
		"first AST (SGOT)",
		"last AST (SGOT)",
		"avg ALT (SGPT)",
		"min ALT (SGPT)",
		"max ALT (SGPT)",
		"first ALT (SGPT)",
		"last ALT (SGPT)",
		"avg PT-INR",
		"min PT-INR",
		"max PT-INR",
		"first PT-INR",
		"last PT-INR",
	--------------------------------------
		case when "Vasopressor" = 1 then 1 else 0 end as "Vasopressor",
		case when "Relaxant" = 1 then 1 else 0 end as "Relaxant",
		case when "Sedation" = 1 then 1 else 0 end as "Sedation",
		case when "PPI" = 1 then 1 else 0 end as "PPI",
		case when "Pain control" = 1 then 1 else 0 end as "Pain control",
	--------------------------------------
		total,
		total2,
		"Fluid_intake_value",
		"Nutrition_Enteral_value",
		"Urine_value",
	--------------------------------------
		case when "Aspergillus" = 1 then 1 else 0 end as "Aspergillus",
		case when "Candida" = 1 then 1 else 0 end as "Candida",
	---
		case when "Abdomen" = 1 then 1 else 0 end as "Abdomen",
		case when "Blood" = 1 then 1 else 0 end as "Blood",
		case when "Respiratory tract" = 1 then 1 else 0 end as "Respiratory tract",
		case when "Skin and soft tissue" = 1 then 1 else 0 end as "Skin and soft tissue",
		case when "Urinary tract" = 1 then 1 else 0 end as "Urinary tract",
		case when "Others" = 1 then 1 else 0 end as "Others",
		--case when "GPB" = 1 then 1 else 0 end as "GPB",
		--case when "GNB" = 1 then 1 else 0 end as "GNB",
		--case when "Fungi" = 1 then 1 else 0 end as "Fungi",

	--------------------------------------
		case when "dod" = 1 then 1 else 0 end as dod
	FROM 
		final
	FULL JOIN  -----------------------
		dod
	ON 
		COALESCE(stay_id_chart,stay_id_lab,stay_id_ingredient,stay_id_intakeoutput,stay_id_micro,stay_id_pc,stay_id_intakeoutput_new) = dod.stay_id_dod and
	    COALESCE(date_chart,date_lab,date_ingredient,date_intakeoutput,date_micro,date_pc,date_intakeoutput_new) = dod.date_dod
)

,final3 as 
(
	SELECT 
		stay_id,
		date,
	--------------------
		MAX("avg SaO2") as "avg SaO2",
		MAX("min SaO2") as "min SaO2",
		MAX("max SaO2") as "max SaO2",
		MAX("first SaO2") as "first SaO2",
		MAX("last SaO2") as "last SaO2",
		MAX("avg Respiration") as "avg Respiration",
		MAX("min Respiration") as "min Respiration",
		MAX("max Respiration") as "max Respiration",
		MAX("first Respiration") as "first Respiration",
		MAX("last Respiration") as "last Respiration",
		MAX("avg Heart Rate") as "avg Heart Rate",
		MAX("min Heart Rate") as "min Heart Rate",
		MAX("max Heart Rate") as "max Heart Rate",
		MAX("first Heart Rate") as "first Heart Rate",
		MAX("last Heart Rate") as "last Heart Rate",
		MAX("avg Systemic Systolic") as "avg Systemic Systolic",
		MAX("min Systemic Systolic") as "min Systemic Systolic",
		MAX("max Systemic Systolic") as "max Systemic Systolic",
		MAX("first Systemic Systolic") as "first Systemic Systolic",
		MAX("last Systemic Systolic") as "last Systemic Systolic",
		MAX("avg Systemic Diastolic") as "avg Systemic Diastolic",
		MAX("min Systemic Diastolic") as "min Systemic Diastolic",
		MAX("max Systemic Diastolic") as "max Systemic Diastolic",
		MAX("first Systemic Diastolic") as "first Systemic Diastolic",
		MAX("last Systemic Diastolic") as "last Systemic Diastolic",
		MAX("avg Systemic Mean") as "avg Systemic Mean",
		MAX("min Systemic Mean") as "min Systemic Mean",
		MAX("max Systemic Mean") as "max Systemic Mean",
		MAX("first Systemic Mean") as "first Systemic Mean",
		MAX("last Systemic Mean") as "last Systemic Mean",
		MAX("avg Compliance") as "avg Compliance",
		MAX("min Compliance") as "min Compliance",
		MAX("max Compliance") as "max Compliance",
		MAX("first Compliance") as "first Compliance",
		MAX("last Compliance") as "last Compliance",
		MAX("avg FiO2") as "avg FiO2",
		MAX("min FiO2") as "min FiO2",
		MAX("max FiO2") as "max FiO2",
		MAX("first FiO2") as "first FiO2",
		MAX("last FiO2") as "last FiO2",
		MAX("avg Minute Ventilation") as "avg Minute Ventilation",
		MAX("min Minute Ventilation") as "min Minute Ventilation",
		MAX("max Minute Ventilation") as "max Minute Ventilation",
		MAX("first Minute Ventilation") as "first Minute Ventilation",
		MAX("last Minute Ventilation") as "last Minute Ventilation",
		MAX("avg Mean Airway Pressure") as "avg Mean Airway Pressure",
		MAX("min Mean Airway Pressure") as "min Mean Airway Pressure",
		MAX("max Mean Airway Pressure") as "max Mean Airway Pressure",
		MAX("first Mean Airway Pressure") as "first Mean Airway Pressure",
		MAX("last Mean Airway Pressure") as "last Mean Airway Pressure",
		MAX("avg Peak Airway Pressure") as "avg Peak Airway Pressure",
		MAX("min Peak Airway Pressure") as "min Peak Airway Pressure",
		MAX("max Peak Airway Pressure") as "max Peak Airway Pressure",
		MAX("first Peak Airway Pressure") as "first Peak Airway Pressure",
		MAX("last Peak Airway Pressure") as "last Peak Airway Pressure",
		MAX("avg PEEP") as "avg PEEP",
		MAX("min PEEP") as "min PEEP",
		MAX("max PEEP") as "max PEEP",
		MAX("first PEEP") as "first PEEP",
		MAX("last PEEP") as "last PEEP",
		MAX("avg PC mode") as "avg PC mode",
		MAX("min PC mode") as "min PC mode",
		MAX("max PC mode") as "max PC mode",
		MAX("first PC mode") as "first PC mode",
		MAX("last PC mode") as "last PC mode",
		MAX("avg Pressure Support") as "avg Pressure Support",
		MAX("min Pressure Support") as "min Pressure Support",
		MAX("max Pressure Support") as "max Pressure Support",
		MAX("first Pressure Support") as "first Pressure Support",
		MAX("last Pressure Support") as "last Pressure Support",
		MAX("avg Plateau") as "avg Plateau",
		MAX("min Plateau") as "min Plateau",
		MAX("max Plateau") as "max Plateau",
		MAX("first Plateau") as "first Plateau",
		MAX("last Plateau") as "last Plateau",
		MAX("avg Tidal Volume") as "avg Tidal Volume",
		MAX("min Tidal Volume") as "min Tidal Volume",
		MAX("max Tidal Volume") as "max Tidal Volume",
		MAX("first Tidal Volume") as "first Tidal Volume",
		MAX("last Tidal Volume") as "last Tidal Volume",
		MAX("avg Respiratory Rate") as "avg Respiratory Rate",
		MAX("min Respiratory Rate") as "min Respiratory Rate",
		MAX("max Respiratory Rate") as "max Respiratory Rate",
		MAX("first Respiratory Rate") as "first Respiratory Rate",
		MAX("last Respiratory Rate") as "last Respiratory Rate",
		MAX("avg ROXindex") as "avg ROXindex",
		MAX("min ROXindex") as "min ROXindex",
		MAX("max ROXindex") as "max ROXindex",
		MAX("first ROXindex") as "first ROXindex",
		MAX("last ROXindex") as "last ROXindex",
		MAX("Daily RSBI") as "Daily RSBI",
		MAX("Unable RSBI") as "Unable RSBI",
		MAX("avg RASS") as "avg RASS",
		MAX("min RASS") as "min RASS",
		MAX("max RASS") as "max RASS",
		MAX("first RASS") as "first RASS",
		MAX("last RASS") as "last RASS",
		MAX("avg Platelets x1000") as "avg Platelets x1000",
		MAX("min Platelets x1000") as "min Platelets x1000",
		MAX("max Platelets x1000") as "max Platelets x1000",
		MAX("first Platelets x1000") as "first Platelets x1000",
		MAX("last Platelets x1000") as "last Platelets x1000",
		MAX("avg WBC x1000") as "avg WBC x1000",
		MAX("min WBC x1000") as "min WBC x1000",
		MAX("max WBC x1000") as "max WBC x1000",
		MAX("first WBC x1000") as "first WBC x1000",
		MAX("last WBC x1000") as "last WBC x1000",
		MAX("avg Hgb") as "avg Hgb",
		MAX("min Hgb") as "min Hgb",
		MAX("max Hgb") as "max Hgb",
		MAX("first Hgb") as "first Hgb",
		MAX("last Hgb") as "last Hgb",
		MAX("avg Albumin") as "avg Albumin",
		MAX("min Albumin") as "min Albumin",
		MAX("max Albumin") as "max Albumin",
		MAX("first Albumin") as "first Albumin",
		MAX("last Albumin") as "last Albumin",
		MAX("avg Total Protein") as "avg Total Protein",
		MAX("min Total Protein") as "min Total Protein",
		MAX("max Total Protein") as "max Total Protein",
		MAX("first Total Protein") as "first Total Protein",
		MAX("last Total Protein") as "last Total Protein",
		MAX("avg Total Bilirubin") as "avg Total Bilirubin",
		MAX("min Total Bilirubin") as "min Total Bilirubin",
		MAX("max Total Bilirubin") as "max Total Bilirubin",
		MAX("first Total Bilirubin") as "first Total Bilirubin",
		MAX("last Total Bilirubin") as "last Total Bilirubin",
		MAX("avg PO2") as "avg PO2",
		MAX("min PO2") as "min PO2",
		MAX("max PO2") as "max PO2",
		MAX("first PO2") as "first PO2",
		MAX("last PO2") as "last PO2",
		MAX("avg PaCO2") as "avg PaCO2",
		MAX("min PaCO2") as "min PaCO2",
		MAX("max PaCO2") as "max PaCO2",
		MAX("first PaCO2") as "first PaCO2",
		MAX("last PaCO2") as "last PaCO2",
		MAX("avg Glucose") as "avg Glucose",
		MAX("min Glucose") as "min Glucose",
		MAX("max Glucose") as "max Glucose",
		MAX("first Glucose") as "first Glucose",
		MAX("last Glucose") as "last Glucose",
		MAX("avg BUN") as "avg BUN",
		MAX("min BUN") as "min BUN",
		MAX("max BUN") as "max BUN",
		MAX("first BUN") as "first BUN",
		MAX("last BUN") as "last BUN",
		MAX("avg pH") as "avg pH",
		MAX("min pH") as "min pH",
		MAX("max pH") as "max pH",
		MAX("first pH") as "first pH",
		MAX("last pH") as "last pH",
		MAX("avg Sodium") as "avg Sodium",
		MAX("min Sodium") as "min Sodium",
		MAX("max Sodium") as "max Sodium",
		MAX("first Sodium") as "first Sodium",
		MAX("last Sodium") as "last Sodium",
		MAX("avg Potassium") as "avg Potassium",
		MAX("min Potassium") as "min Potassium",
		MAX("max Potassium") as "max Potassium",
		MAX("first Potassium") as "first Potassium",
		MAX("last Potassium") as "last Potassium",
		MAX("avg Magnesium") as "avg Magnesium",
		MAX("min Magnesium") as "min Magnesium",
		MAX("max Magnesium") as "max Magnesium",
		MAX("first Magnesium") as "first Magnesium",
		MAX("last Magnesium") as "last Magnesium",
		MAX("avg Calcium") as "avg Calcium",
		MAX("min Calcium") as "min Calcium",
		MAX("max Calcium") as "max Calcium",
		MAX("first Calcium") as "first Calcium",
		MAX("last Calcium") as "last Calcium",
		MAX("avg Chloride") as "avg Chloride",
		MAX("min Chloride") as "min Chloride",
		MAX("max Chloride") as "max Chloride",
		MAX("first Chloride") as "first Chloride",
		MAX("last Chloride") as "last Chloride",
		MAX("avg creatinine") as "avg creatinine",
		MAX("min creatinine") as "min creatinine",
		MAX("max creatinine") as "max creatinine",
		MAX("first creatinine") as "first creatinine",
		MAX("last creatinine") as "last creatinine",
		MAX("avg HCO3") as "avg HCO3",
		MAX("min HCO3") as "min HCO3",
		MAX("max HCO3") as "max HCO3",
		MAX("first HCO3") as "first HCO3",
		MAX("last HCO3") as "last HCO3",
		MAX("avg Phosphate") as "avg Phosphate",
		MAX("min Phosphate") as "min Phosphate",
		MAX("max Phosphate") as "max Phosphate",
		MAX("first Phosphate") as "first Phosphate",
		MAX("last Phosphate") as "last Phosphate",
		MAX("avg Alkaline Phos.") as "avg Alkaline Phos.",
		MAX("min Alkaline Phos.") as "min Alkaline Phos.",
		MAX("max Alkaline Phos.") as "max Alkaline Phos.",
		MAX("first Alkaline Phos.") as "first Alkaline Phos.",
		MAX("last Alkaline Phos.") as "last Alkaline Phos.",
		MAX("avg AST (SGOT)") as "avg AST (SGOT)",
		MAX("min AST (SGOT)") as "min AST (SGOT)",
		MAX("max AST (SGOT)") as "max AST (SGOT)",
		MAX("first AST (SGOT)") as "first AST (SGOT)",
		MAX("last AST (SGOT)") as "last AST (SGOT)",
		MAX("avg ALT (SGPT)") as "avg ALT (SGPT)",
		MAX("min ALT (SGPT)") as "min ALT (SGPT)",
		MAX("max ALT (SGPT)") as "max ALT (SGPT)",
		MAX("first ALT (SGPT)") as "first ALT (SGPT)",
		MAX("last ALT (SGPT)") as "last ALT (SGPT)",
		MAX("avg PT-INR") as "avg PT-INR",
		MAX("min PT-INR") as "min PT-INR",
		MAX("max PT-INR") as "max PT-INR",
		MAX("first PT-INR") as "first PT-INR",
		MAX("last PT-INR") as "last PT-INR",
		MAX("Vasopressor") as "Vasopressor",
		MAX("Relaxant") as "Relaxant",
		MAX("Sedation") as "Sedation",
		MAX("PPI") as "PPI",
		MAX("Pain control") as "Pain control",
		MAX("total") as "total",
		MAX("total2") as "total2",
		MAX("Fluid_intake_value") as "Fluid_intake_value",
		MAX("Nutrition_Enteral_value") as "Nutrition_Enteral_value",
		MAX("Urine_value") as "Urine_value",
		MAX("Aspergillus") as "Aspergillus",
		MAX("Candida") as "Candida",
		MAX("Abdomen") as "Abdomen",
		MAX("Blood") as "Blood",
		MAX("Respiratory tract") as "Respiratory tract",
		MAX("Skin and soft tissue") as "Skin and soft tissue",
		MAX("Urinary tract") as "Urinary tract",
		MAX("Others") as "Others",
		MAX("dod") as "dod"
	FROM 
		final2
	GROUP BY
		stay_id,
		date
)

select * from final3

