DROP table IF EXISTS data_9.final_fusion_with_vent_plus; 
create table data_9.final_fusion_with_vent_plus AS

/*
dod   30d、60d、90d
*/

with dod_date AS
(
	SELECT
		stay_id AS dod_stay_id,
		dod AS dod_date
	FROM
		data_9.icu_detail

)
-- remain days
, add_dod as 
(
	SELECT 
		stay_id,
		date,
		dod,
		dod_date,
		CAST(date_part('day', dod_date - date) AS INT) AS remain_dod_day
	FROM
		data_9.final_fusion_with_vent
	LEFT JOIN
		dod_date
	ON
		data_9.final_fusion_with_vent.stay_id = dod_date.dod_stay_id
)
-- 30day、60day、90day label
, add_dod_label as 
(
	SELECT
		stay_id,
		date,
		dod,
		dod_date,
		remain_dod_day,
		CASE when remain_dod_day <= 30  then 1 else 0 end as dod_30day,
		CASE when remain_dod_day <= 60  then 1 else 0 end as dod_60day,
		CASE when remain_dod_day <= 90  then 1 else 0 end as dod_90day
	FROM
		add_dod
)

, final_table as
(
	SELECT 
		main.stay_id,
		main.date,
	--------------------
		"avg SaO2",
		--"min SaO2",
		--"max SaO2",
		--"first SaO2",
		--"last SaO2",
		"avg Respiration",
		--"min Respiration",
		--"max Respiration",
		--"first Respiration",
		--"last Respiration",
		"avg Heart Rate",
		--"min Heart Rate",
		--"max Heart Rate",
		--"first Heart Rate",
		--"last Heart Rate",
		"avg Systemic Systolic",
		--"min Systemic Systolic",
		--"max Systemic Systolic",
		--"first Systemic Systolic",
		--"last Systemic Systolic",
		"avg Systemic Diastolic",
		--"min Systemic Diastolic",
		--"max Systemic Diastolic",
		--"first Systemic Diastolic",
		--"last Systemic Diastolic",
		"avg Systemic Mean",
		--"min Systemic Mean",
		--"max Systemic Mean",
		--"first Systemic Mean",
		--"last Systemic Mean",
		"avg Compliance",
		--"min Compliance",
		--"max Compliance",
		--"first Compliance",
		--"last Compliance",
		"avg FiO2",
		--"min FiO2",
		--"max FiO2",
		--"first FiO2",
		--"last FiO2",
		"avg Minute Ventilation",
		--"min Minute Ventilation",
		--"max Minute Ventilation",
		--"first Minute Ventilation",
		--"last Minute Ventilation",
		"avg Mean Airway Pressure",
		--"min Mean Airway Pressure",
		--"max Mean Airway Pressure",
		--"first Mean Airway Pressure",
		--"last Mean Airway Pressure",
		"avg Peak Airway Pressure",
		--"min Peak Airway Pressure",
		--"max Peak Airway Pressure",
		--"first Peak Airway Pressure",
		--"last Peak Airway Pressure",
		"avg PEEP",
		--"min PEEP",
		--"max PEEP",
		--"first PEEP",
		--"last PEEP",
		"avg PC mode",
		--"min PC mode",
		--"max PC mode",
		--"first PC mode",
		--"last PC mode",
		"avg Pressure Support",
		--"min Pressure Support",
		--"max Pressure Support",
		--"first Pressure Support",
		--"last Pressure Support",
		"avg Plateau",
		--"min Plateau",
		--"max Plateau",
		--"first Plateau",
		--"last Plateau",
		"avg Tidal Volume",
		--"min Tidal Volume",
		--"max Tidal Volume",
		--"first Tidal Volume",
		--"last Tidal Volume",
		"avg Respiratory Rate",
		--"min Respiratory Rate",
		--"max Respiratory Rate",
		--"first Respiratory Rate",
		--"last Respiratory Rate",
		"avg ROXindex",
		--"min ROXindex",
		--"max ROXindex",
		--"first ROXindex",
		--"last ROXindex",
		--"Daily RSBI",
		--"Unable RSBI",
		"avg RASS",
		--"min RASS",
		--"max RASS",
		--"first RASS",
		--"last RASS",
		"avg Platelets x1000",
		--"min Platelets x1000",
		--"max Platelets x1000",
		--"first Platelets x1000",
		--"last Platelets x1000",
		"avg WBC x1000",
		--"min WBC x1000",
		--"max WBC x1000",
		--"first WBC x1000",
		--"last WBC x1000",
		"avg Hgb",
		--"min Hgb",
		--"max Hgb",
		--"first Hgb",
		--"last Hgb",
		"avg Albumin",
		--"min Albumin",
		--"max Albumin",
		--"first Albumin",
		--"last Albumin",
		"avg Total Protein",
		--"min Total Protein",
		--"max Total Protein",
		--"first Total Protein",
		--"last Total Protein",
		"avg Total Bilirubin",
		--"min Total Bilirubin",
		--"max Total Bilirubin",
		--"first Total Bilirubin",
		--"last Total Bilirubin",
		"avg PO2",
		--"min PO2",
		--"max PO2",
		--"first PO2",
		--"last PO2",
		"avg PaCO2",
		--"min PaCO2",
		--"max PaCO2",
		--"first PaCO2",
		--"last PaCO2",
		"avg Glucose",
		--"min Glucose",
		--"max Glucose",
		--"first Glucose",
		--"last Glucose",
		"avg BUN",
		--"min BUN",
		--"max BUN",
		--"first BUN",
		--"last BUN",
		"avg pH",
		--"min pH",
		--"max pH",
		--"first pH",
		--"last pH",
		"avg Sodium",
		--"min Sodium",
		--"max Sodium",
		--"first Sodium",
		--"last Sodium",
		"avg Potassium",
		--"min Potassium",
		--"max Potassium",
		--"first Potassium",
		--"last Potassium",
		"avg Magnesium",
		--"min Magnesium",
		--"max Magnesium",
		--"first Magnesium",
		--"last Magnesium",
		"avg Calcium",
		--"min Calcium",
		--"max Calcium",
		--"first Calcium",
		--"last Calcium",
		"avg Chloride",
		--"min Chloride",
		--"max Chloride",
		--"first Chloride",
		--"last Chloride",
		"avg creatinine",
		--"min creatinine",
		--"max creatinine",
		--"first creatinine",
		--"last creatinine",
		"avg HCO3",
		--"min HCO3",
		--"max HCO3",
		--"first HCO3",
		--"last HCO3",
		"avg Phosphate",
		--"min Phosphate",
		--"max Phosphate",
		--"first Phosphate",
		--"last Phosphate",
		"avg Alkaline Phos.",
		--"min Alkaline Phos.",
		--"max Alkaline Phos.",
		--"first Alkaline Phos.",
		--"last Alkaline Phos.",
		"avg AST (SGOT)",
		--"min AST (SGOT)",
		--"max AST (SGOT)",
		--"first AST (SGOT)",
		--"last AST (SGOT)",
		"avg ALT (SGPT)",
		--"min ALT (SGPT)",
		--"max ALT (SGPT)",
		--"first ALT (SGPT)",
		--"last ALT (SGPT)",
		"avg PT-INR",
		--"min PT-INR",
		--"max PT-INR",
		--"first PT-INR",
		--"last PT-INR",
		"Vasopressor",
		"Relaxant",
		"Sedation",
		"PPI",
		"Pain control",
		"total",
		"total2",
		"Fluid_intake_value",
		"Nutrition_Enteral_value",
		"Urine_value",
		"Aspergillus",
		"Candida",
		"Abdomen",
		"Blood",
		"Respiratory tract",
		"Skin and soft tissue",
		"Urinary tract",
		"Others",
		------------死亡------------
		main.dod,
		dod_30day,
		dod_60day,
		dod_90day,
		------------呼吸器------------
		"InvasiveVent",
		"tracheostomy",
		"NonInvasiveVent",
		"SupplementalOxygen",
		"HFNC",
		"SBT Started",
		"SBT Successfully Completed",
	------------------------------------------------------------------------
		gender,
		age,
		race,
		dnr,
		apsiii,
		------疾病---------------
		"MI",
		"CHF",
		"PVD",
		"CVD",
		"Dementia",
		"CPD",
		"RD",
		"PUD",
		"MLD",
		"DM_acute",
		"DM_Chronic",
		"Hemiplegia",
		"Renal",
		"Malignancy",
		"LD",
		"MST",
		"AIDS",
		------LAB---------------
		"Troponin - I", 
		"Troponin - T",
		"Ferritin",
		"Transferrin",
		--找不到Prealbumin,
		"CRP",
		"Fibrinogen",
		"HDL",
		"LDL",
		"Total Cholesterol",
		"Direct Bilirubin",
		"Lactate",
		"LDH",
		"Lipase",
		"Amylase",
		"CPK",
		"CPK-MB",
		--"CPK-MB_INDEX"  -----==> 不重要,
		"BNP",
		"PTT",
		"PTT_Ratio", -------找不到 ==>20230130用算的
		"Fe",
		"TIBC",
		"Fe/TIBC Ratio", -------用算的
		"Serum_Osmolality",
		"TSH",
		"T3",
		"T4",
		"Free T4",
		"Ionized Calcium",
		"Triglycerides",
		"Cortisol",
		"Uric Acid",
		"Ammonia",
		"Vitamin B12"
	FROM
		data_9.final_fusion_with_vent as main
	LEFT JOIN
		add_dod_label
	ON
		main.stay_id = add_dod_label.stay_id and main.date = add_dod_label.date
)

SELECT * FROM final_table