---統計用 => 用來看每個人 有幾天有資料
SELECT
	stay_id,
	SUM("Anxiety") AS "Anxiety",
	SUM("Assess for anxiety, depression, or delirium which may contribut") AS "Assess for anxiety, depression, or delirium which may contribut",
	SUM("Asystole") AS "Asystole",
	SUM("Blood Transfusion") AS "Blood Transfusion",
	SUM("Consult to pastoral care, social services, palliative care, psy") AS "Consult to pastoral care, social services, palliative care, psy",
	SUM("DNAR (Do Not Attempt Resuscitation) [DNR]") AS "DNAR (Do Not Attempt Resuscitation) [DNR]",
	SUM("DNAR (Do Not Attempt Resuscitation) [DNR] / DNI") AS "DNAR (Do Not Attempt Resuscitation) [DNR] / DNI",
	SUM("DNI (do not intubate)") AS "DNI (do not intubate)",
	SUM("DNR (do not resuscitate)") AS "DNR (do not resuscitate)",
	SUM("DNR / DNI") AS "DNR / DNI",
	SUM("Early mobilization") AS "Early mobilization",
	SUM("Encourage family to participate in care") AS "Encourage family to participate in care",
	SUM("Encourage patient / family members to accept individual reponse") AS "Encourage patient / family members to accept individual reponse",
	SUM("Encourage patient / family to set and verbalize care goals") AS "Encourage patient / family to set and verbalize care goals",
	SUM("Enlist family support / family sitters") AS "Enlist family support / family sitters",
	SUM("Explanation") AS "Explanation",
	SUM("Family at bedside") AS "Family at bedside",
	SUM("Family Called") AS "Family Called",
	SUM("Family Conference") AS "Family Conference",
	SUM("Family Member") AS "Family Member",
	SUM("Family Talked to MD") AS "Family Talked to MD",
	SUM("Family Talked to RN") AS "Family Talked to RN",
	SUM("Family Visited") AS "Family Visited",
	SUM("Full code") AS "Full code",
	SUM("Full resistance") AS "Full resistance",
	SUM("Fully awake") AS "Fully awake",
	SUM("Listen attentively when patient attempts to communicate") AS "Listen attentively when patient attempts to communicate",
	SUM("Liver Failure") AS "Liver Failure",
	SUM("Manage environment for patient''s maximum comfort") AS "Manage environment for patient''s maximum comfort",
	SUM("Maintain GCS >= 8") AS "Maintain GCS >= 8",
	SUM("No Proxy") AS "No Proxy",
	SUM("No, not sedated") AS "No, not sedated",
	SUM("Palliative Care") AS "Palliative Care",
	SUM("Patient / family involved in treatment plan") AS "Patient / family involved in treatment plan",
	SUM("Patient / family will have adequate support once CMO decision h") AS "Patient / family will have adequate support once CMO decision h",
	SUM("Patient / family will have support throughout the dying process") AS "Patient / family will have support throughout the dying process",
	SUM("Patient / family will participate in planning and initiating cu") AS "Patient / family will participate in planning and initiating cu",
	SUM("Patient refused") AS "Patient refused",
	SUM("Patient Verbalized") AS "Patient Verbalized",
	SUM("Promote early mobility") AS "Promote early mobility",
	SUM("Rehab") AS "Rehab",
	SUM("Rehabilitation") AS "Rehabilitation",
	SUM("SBT") AS "SBT",
	SUM("Social Service Involved") AS "Social Service Involved",
	SUM("Social Services") AS "Social Services",
	SUM("Social Work") AS "Social Work",
	SUM("Spiritual") AS "Spiritual",
	SUM("Spouse") AS "Spouse",
	SUM("Thermoregulation") AS "Thermoregulation",
	SUM("TPN") AS "TPN",
	SUM("Tracheostomy") AS "Tracheostomy",
	SUM("Tracheostomy tube") AS "Tracheostomy tube",
	SUM("With family") AS "With family",
	SUM("With spouse") AS "With spouse",
	SUM("Withdraws") AS "Withdraws"
FROM 
	pj_dnr.mini_chart_date
GROUP BY 
	stay_id