DROP table IF EXISTS pj_dnr.target;  
create table pj_dnr.target AS

--加DNR相關特徵table
WITH target1 as 
(
	SELECT 
		original_table.stay_id,
		original_table.date,
	--------------------
		"avg SaO2",
		"avg Respiration",
		"avg Heart Rate",
		"avg Systemic Systolic",
		"avg Systemic Diastolic",
		"avg Systemic Mean",
		"avg Compliance",
		"avg FiO2",
		"avg Minute Ventilation",
		"avg Mean Airway Pressure",
		"avg Peak Airway Pressure",
		"avg PEEP",
		"avg PC mode",
		"avg Pressure Support",
		"avg Plateau",
		"avg Tidal Volume",
		"avg Respiratory Rate",
		"avg ROXindex",
		--"Daily RSBI",
		--"Unable RSBI",
		"avg RASS",
		"avg Platelets x1000",
		"avg WBC x1000",
		"avg Hgb",
		"avg Albumin",
		"avg Total Protein",
		"avg Total Bilirubin",
		"avg PO2",
		"avg PaCO2",
		"avg Glucose",
		"avg BUN",
		"avg pH",
		"avg Sodium",
		"avg Potassium",
		"avg Magnesium",
		"avg Calcium",
		"avg Chloride",
		"avg creatinine",
		"avg HCO3",
		"avg Phosphate",
		"avg Alkaline Phos.",
		"avg AST (SGOT)",
		"avg ALT (SGPT)",
		"avg PT-INR",
		"Vasopressor",
		"Relaxant",
		"Sedation",
		"PPI",
		"Pain control",
		"total",
		"total2",
		"Fluid_intake_value",
		"Nutrition_Enteral_value",
		"Urine_value",
		"Aspergillus",
		"Candida",
		"Abdomen",
		"Blood",
		"Respiratory tract",
		"Skin and soft tissue",
		"Urinary tract",
		"Others",
		------------死亡------------
		dod,
		dod_3day,
		dod_7day,
		dod_30day,
		dod_60day,
		dod_90day,
		------------呼吸器------------
		"InvasiveVent",
		"tracheostomy",
		"NonInvasiveVent",
		"SupplementalOxygen",
		"HFNC",
		--"SBT Started",
		--"SBT Successfully Completed",
	--------------DNR相關-----------------------------
		"Anxiety",
		"Assess for anxiety, depression, or delirium which may contribut",
		"Asystole",
		"Blood Transfusion",
		"Consult to pastoral care, social services, palliative care, psy",
		"DNAR (Do Not Attempt Resuscitation) [DNR]",
		"DNAR (Do Not Attempt Resuscitation) [DNR] / DNI",
		"DNI (do not intubate)",
		"DNR (do not resuscitate)",
		"DNR / DNI",
		"Early mobilization",
		"Encourage family to participate in care",
		"Encourage patient / family members to accept individual reponse",
		"Encourage patient / family to set and verbalize care goals",
		"Enlist family support / family sitters",
		"Explanation",
		"Family at bedside",
		"Family Called",
		"Family Conference",
		"Family Member",
		"Family Talked to MD",
		"Family Talked to RN",
		"Family Visited",
		"Full code",
		"Full resistance",
		"Fully awake",
		"Listen attentively when patient attempts to communicate",
		"Liver Failure",
		"Manage environment for patient''s maximum comfort",
		"Maintain GCS >= 8",
		"No Proxy",
		"No, not sedated",
		"Palliative Care",
		"Patient / family involved in treatment plan",
		"Patient / family will have adequate support once CMO decision h",
		"Patient / family will have support throughout the dying process",
		"Patient / family will participate in planning and initiating cu",
		"Patient refused",
		"Patient Verbalized",
		"Promote early mobility",
		"Rehab",
		"Rehabilitation",
		"SBT",
		"Social Service Involved",
		"Social Services",
		"Social Work",
		"Spiritual",
		"Spouse",
		"Thermoregulation",
		"TPN",
		"Tracheostomy",
		"Tracheostomy tube",
		"With family",
		"With spouse",
		"Withdraws",

	------------------------------------------------------------------------
		gender,
		age,
		race,
		dnr,
		apsiii,
		------疾病---------------
		"MI",
		"CHF",
		"PVD",
		"CVD",
		"Dementia",
		"CPD",
		"RD",
		"PUD",
		"MLD",
		"DM_acute",
		"DM_Chronic",
		"Hemiplegia",
		"Renal",
		"Malignancy",
		"LD",
		"MST",
		"AIDS",
		------LAB---------------
		"Troponin - I", 
		"Troponin - T",
		"Ferritin",
		"Transferrin",
		--找不到Prealbumin,
		"CRP",
		"Fibrinogen",
		"HDL",
		"LDL",
		"Total Cholesterol",
		"Direct Bilirubin",
		"Lactate",
		"LDH",
		"Lipase",
		"Amylase",
		"CPK",
		"CPK-MB",
		"BNP",
		"PTT",
		"PTT_Ratio", 
		"Fe",
		"TIBC",
		"Fe/TIBC Ratio", 
		"Serum_Osmolality",
		"TSH",
		"T3",
		"T4",
		"Free T4",
		"Ionized Calcium",
		"Triglycerides",
		"Cortisol",
		"Uric Acid",
		"Ammonia",
		"Vitamin B12" 
	FROM 
		data_9.final_fusion_with_vent_plus as original_table
	FULL JOIN
		pj_dnr.mini_chart_date as DNR_table
	ON
		original_table.stay_id = DNR_table.stay_id and original_table.date = DNR_table.date
)
--加入抗生素
, target2 as 
(
	SELECT
		target1.stay_id,
		target1.date,
	--------------------
		"avg SaO2",
		"avg Respiration",
		"avg Heart Rate",
		"avg Systemic Systolic",
		"avg Systemic Diastolic",
		"avg Systemic Mean",
		"avg Compliance",
		"avg FiO2",
		"avg Minute Ventilation",
		"avg Mean Airway Pressure",
		"avg Peak Airway Pressure",
		"avg PEEP",
		"avg PC mode",
		"avg Pressure Support",
		"avg Plateau",
		"avg Tidal Volume",
		"avg Respiratory Rate",
		"avg ROXindex",
		"avg RASS",
		"avg Platelets x1000",
		"avg WBC x1000",
		"avg Hgb",
		"avg Albumin",
		"avg Total Protein",
		"avg Total Bilirubin",
		"avg PO2",
		"avg PaCO2",
		"avg Glucose",
		"avg BUN",
		"avg pH",
		"avg Sodium",
		"avg Potassium",
		"avg Magnesium",
		"avg Calcium",
		"avg Chloride",
		"avg creatinine",
		"avg HCO3",
		"avg Phosphate",
		"avg Alkaline Phos.",
		"avg AST (SGOT)",
		"avg ALT (SGPT)",
		"avg PT-INR",
		"Vasopressor",
		"Relaxant",
		"Sedation",
		"PPI",
		"Pain control",
		"total",
		"total2",
		"Fluid_intake_value",
		"Nutrition_Enteral_value",
		"Urine_value",
		"Aspergillus",
		"Candida",
		"Abdomen",
		"Blood",
		"Respiratory tract",
		"Skin and soft tissue",
		"Urinary tract",
		"Others",
		------------死亡------------
		dod,
		dod_3day,
		dod_7day,
		dod_30day,
		dod_60day,
		dod_90day,
		------------呼吸器------------
		"InvasiveVent",
		"tracheostomy",
		"NonInvasiveVent",
		"SupplementalOxygen",
		"HFNC",
		--"SBT Started",
		--"SBT Successfully Completed",
	    ----------DNR相關-------------
		"Anxiety",
		"Assess for anxiety, depression, or delirium which may contribut",
		"Asystole",
		"Blood Transfusion",
		"Consult to pastoral care, social services, palliative care, psy",
		"DNAR (Do Not Attempt Resuscitation) [DNR]",
		"DNAR (Do Not Attempt Resuscitation) [DNR] / DNI",
		"DNI (do not intubate)",
		"DNR (do not resuscitate)",
		"DNR / DNI",
		"Early mobilization",
		"Encourage family to participate in care",
		"Encourage patient / family members to accept individual reponse",
		"Encourage patient / family to set and verbalize care goals",
		"Enlist family support / family sitters",
		"Explanation",
		"Family at bedside",
		"Family Called",
		"Family Conference",
		"Family Member",
		"Family Talked to MD",
		"Family Talked to RN",
		"Family Visited",
		"Full code",
		"Full resistance",
		"Fully awake",
		"Listen attentively when patient attempts to communicate",
		"Liver Failure",
		"Manage environment for patient''s maximum comfort",
		"Maintain GCS >= 8",
		"No Proxy",
		"No, not sedated",
		"Palliative Care",
		"Patient / family involved in treatment plan",
		"Patient / family will have adequate support once CMO decision h",
		"Patient / family will have support throughout the dying process",
		"Patient / family will participate in planning and initiating cu",
		"Patient refused",
		"Patient Verbalized",
		"Promote early mobility",
		"Rehab",
		"Rehabilitation",
		"SBT",
		"Social Service Involved",
		"Social Services",
		"Social Work",
		"Spiritual",
		"Spouse",
		"Thermoregulation",
		"TPN",
		"Tracheostomy",
		"Tracheostomy tube",
		"With family",
		"With spouse",
		"Withdraws",
		----------抗生素----------
		antibiotic,
	------------------------------------------------------------------------
		gender,
		age,
		race,
		dnr,
		apsiii,
		------疾病---------------
		"MI",
		"CHF",
		"PVD",
		"CVD",
		"Dementia",
		"CPD",
		"RD",
		"PUD",
		"MLD",
		"DM_acute",
		"DM_Chronic",
		"Hemiplegia",
		"Renal",
		"Malignancy",
		"LD",
		"MST",
		"AIDS",
		------LAB---------------
		"Troponin - I", 
		"Troponin - T",
		"Ferritin",
		"Transferrin",
		--找不到Prealbumin,
		"CRP",
		"Fibrinogen",
		"HDL",
		"LDL",
		"Total Cholesterol",
		"Direct Bilirubin",
		"Lactate",
		"LDH",
		"Lipase",
		"Amylase",
		"CPK",
		"CPK-MB",
		"BNP",
		"PTT",
		"PTT_Ratio", 
		"Fe",
		"TIBC",
		"Fe/TIBC Ratio", 
		"Serum_Osmolality",
		"TSH",
		"T3",
		"T4",
		"Free T4",
		"Ionized Calcium",
		"Triglycerides",
		"Cortisol",
		"Uric Acid",
		"Ammonia",
		"Vitamin B12" 
	FROM
		target1
	LEFT JOIN
		pj_dnr.antibiotic_date as antibiotic
	ON
	   (target1.stay_id = antibiotic.stay_id and target1.date >=antibiotic.starttime) and
	   (target1.stay_id = antibiotic.stay_id and target1.date <= antibiotic.endtime) 
)
-- 加入抗生素會產生同天多筆，取MAX， => 用python產SQL
, target3 AS
(
	SELECT
		stay_id,
		date,
		MAX("avg SaO2") AS "avg SaO2",
		MAX("avg Respiration") AS "avg Respiration",
		MAX("avg Heart Rate") AS "avg Heart Rate",
		MAX("avg Systemic Systolic") AS "avg Systemic Systolic",
		MAX("avg Systemic Diastolic") AS "avg Systemic Diastolic",
		MAX("avg Systemic Mean") AS "avg Systemic Mean",
		MAX("avg Compliance") AS "avg Compliance",
		MAX("avg FiO2") AS "avg FiO2",
		MAX("avg Minute Ventilation") AS "avg Minute Ventilation",
		MAX("avg Mean Airway Pressure") AS "avg Mean Airway Pressure",
		MAX("avg Peak Airway Pressure") AS "avg Peak Airway Pressure",
		MAX("avg PEEP") AS "avg PEEP",
		"avg PC mode",
		MAX("avg Pressure Support") AS "avg Pressure Support",
		MAX("avg Plateau") AS "avg Plateau",
		MAX("avg Tidal Volume") AS "avg Tidal Volume",
		MAX("avg Respiratory Rate") AS "avg Respiratory Rate",
		MAX("avg ROXindex") AS "avg ROXindex",
		MAX("avg RASS") AS "avg RASS",
		MAX("avg Platelets x1000") AS "avg Platelets x1000",
		MAX("avg WBC x1000") AS "avg WBC x1000",
		MAX("avg Hgb") AS "avg Hgb",
		MAX("avg Albumin") AS "avg Albumin",
		MAX("avg Total Protein") AS "avg Total Protein",
		MAX("avg Total Bilirubin") AS "avg Total Bilirubin",
		MAX("avg PO2") AS "avg PO2",
		MAX("avg PaCO2") AS "avg PaCO2",
		MAX("avg Glucose") AS "avg Glucose",
		MAX("avg BUN") AS "avg BUN",
		MAX("avg pH") AS "avg pH",
		MAX("avg Sodium") AS "avg Sodium",
		MAX("avg Potassium") AS "avg Potassium",
		MAX("avg Magnesium") AS "avg Magnesium",
		MAX("avg Calcium") AS "avg Calcium",
		MAX("avg Chloride") AS "avg Chloride",
		MAX("avg creatinine") AS "avg creatinine",
		MAX("avg HCO3") AS "avg HCO3",
		MAX("avg Phosphate") AS "avg Phosphate",
		MAX("avg Alkaline Phos.") AS "avg Alkaline Phos.",
		MAX("avg AST (SGOT)") AS "avg AST (SGOT)",
		MAX("avg ALT (SGPT)") AS "avg ALT (SGPT)",
		MAX("avg PT-INR") AS "avg PT-INR",
		MAX("Vasopressor") AS "Vasopressor",
		MAX("Relaxant") AS "Relaxant",
		MAX("Sedation") AS "Sedation",
		MAX("PPI") AS "PPI",
		MAX("Pain control") AS "Pain control",
		MAX("total") AS "total",
		MAX("total2") AS "total2",
		MAX("Fluid_intake_value") AS "Fluid_intake_value",
		MAX("Nutrition_Enteral_value") AS "Nutrition_Enteral_value",
		MAX("Urine_value") AS "Urine_value",
		MAX("Aspergillus") AS "Aspergillus",
		MAX("Candida") AS "Candida",
		MAX("Abdomen") AS "Abdomen",
		MAX("Blood") AS "Blood",
		MAX("Respiratory tract") AS "Respiratory tract",
		MAX("Skin and soft tissue") AS "Skin and soft tissue",
		MAX("Urinary tract") AS "Urinary tract",
		MAX("Others") AS "Others",
		MAX(dod) AS dod,
		MAX(dod_3day) AS dod_3day,
		MAX(dod_7day) AS dod_7day,
		MAX(dod_30day) AS dod_30day,
		MAX(dod_60day) AS dod_60day,
		MAX(dod_90day) AS dod_90day,
		MAX("InvasiveVent") AS "InvasiveVent",
		MAX("tracheostomy") AS "tracheostomy",
		MAX("NonInvasiveVent") AS "NonInvasiveVent",
		MAX("SupplementalOxygen") AS "SupplementalOxygen",
		MAX("HFNC") AS "HFNC",
		MAX("Anxiety") AS "Anxiety",
		MAX("Assess for anxiety, depression, or delirium which may contribut") AS "Assess for anxiety, depression, or delirium which may contribut",
		MAX("Asystole") AS "Asystole",
		MAX("Blood Transfusion") AS "Blood Transfusion",
		MAX("Consult to pastoral care, social services, palliative care, psy") AS "Consult to pastoral care, social services, palliative care, psy",
		MAX("DNAR (Do Not Attempt Resuscitation) [DNR]") AS "DNAR (Do Not Attempt Resuscitation) [DNR]",
		MAX("DNAR (Do Not Attempt Resuscitation) [DNR] / DNI") AS "DNAR (Do Not Attempt Resuscitation) [DNR] / DNI",
		MAX("DNI (do not intubate)") AS "DNI (do not intubate)",
		MAX("DNR (do not resuscitate)") AS "DNR (do not resuscitate)",
		MAX("DNR / DNI") AS "DNR / DNI",
		MAX("Early mobilization") AS "Early mobilization",
		MAX("Encourage family to participate in care") AS "Encourage family to participate in care",
		MAX("Encourage patient / family members to accept individual reponse") AS "Encourage patient / family members to accept individual reponse",
		MAX("Encourage patient / family to set and verbalize care goals") AS "Encourage patient / family to set and verbalize care goals",
		MAX("Enlist family support / family sitters") AS "Enlist family support / family sitters",
		MAX("Explanation") AS "Explanation",
		MAX("Family at bedside") AS "Family at bedside",
		MAX("Family Called") AS "Family Called",
		MAX("Family Conference") AS "Family Conference",
		MAX("Family Member") AS "Family Member",
		MAX("Family Talked to MD") AS "Family Talked to MD",
		MAX("Family Talked to RN") AS "Family Talked to RN",
		MAX("Family Visited") AS "Family Visited",
		MAX("Full code") AS "Full code",
		MAX("Full resistance") AS "Full resistance",
		MAX("Fully awake") AS "Fully awake",
		MAX("Listen attentively when patient attempts to communicate") AS "Listen attentively when patient attempts to communicate",
		MAX("Liver Failure") AS "Liver Failure",
		MAX("Manage environment for patient''s maximum comfort") AS "Manage environment for patient''s maximum comfort",
		MAX("Maintain GCS >= 8") AS "Maintain GCS >= 8",
		MAX("No Proxy") AS "No Proxy",
		MAX("No, not sedated") AS "No, not sedated",
		MAX("Palliative Care") AS "Palliative Care",
		MAX("Patient / family involved in treatment plan") AS "Patient / family involved in treatment plan",
		MAX("Patient / family will have adequate support once CMO decision h") AS "Patient / family will have adequate support once CMO decision h",
		MAX("Patient / family will have support throughout the dying process") AS "Patient / family will have support throughout the dying process",
		MAX("Patient / family will participate in planning and initiating cu") AS "Patient / family will participate in planning and initiating cu",
		MAX("Patient refused") AS "Patient refused",
		MAX("Patient Verbalized") AS "Patient Verbalized",
		MAX("Promote early mobility") AS "Promote early mobility",
		MAX("Rehab") AS "Rehab",
		MAX("Rehabilitation") AS "Rehabilitation",
		MAX("SBT") AS "SBT",
		MAX("Social Service Involved") AS "Social Service Involved",
		MAX("Social Services") AS "Social Services",
		MAX("Social Work") AS "Social Work",
		MAX("Spiritual") AS "Spiritual",
		MAX("Spouse") AS "Spouse",
		MAX("Thermoregulation") AS "Thermoregulation",
		MAX("TPN") AS "TPN",
		MAX("Tracheostomy") AS "Tracheostomy",
		MAX("Tracheostomy tube") AS "Tracheostomy tube",
		MAX("With family") AS "With family",
		MAX("With spouse") AS "With spouse",
		MAX("Withdraws") AS "Withdraws",
		MAX(antibiotic) AS antibiotic,
		gender,
		MAX(age) AS age,
		race,
		MAX(dnr) AS dnr,
		MAX(apsiii) AS apsiii,
		MAX("MI") AS "MI",
		MAX("CHF") AS "CHF",
		MAX("PVD") AS "PVD",
		MAX("CVD") AS "CVD",
		MAX("Dementia") AS "Dementia",
		MAX("CPD") AS "CPD",
		MAX("RD") AS "RD",
		MAX("PUD") AS "PUD",
		MAX("MLD") AS "MLD",
		MAX("DM_acute") AS "DM_acute",
		MAX("DM_Chronic") AS "DM_Chronic",
		MAX("Hemiplegia") AS "Hemiplegia",
		MAX("Renal") AS "Renal",
		MAX("Malignancy") AS "Malignancy",
		MAX("LD") AS "LD",
		MAX("MST") AS "MST",
		MAX("AIDS") AS "AIDS",
		MAX("Troponin - I") AS "Troponin - I",
		MAX("Troponin - T") AS "Troponin - T",
		MAX("Ferritin") AS "Ferritin",
		MAX("Transferrin") AS "Transferrin",
		MAX("CRP") AS "CRP",
		MAX("Fibrinogen") AS "Fibrinogen",
		MAX("HDL") AS "HDL",
		MAX("LDL") AS "LDL",
		MAX("Total Cholesterol") AS "Total Cholesterol",
		MAX("Direct Bilirubin") AS "Direct Bilirubin",
		MAX("Lactate") AS "Lactate",
		MAX("LDH") AS "LDH",
		MAX("Lipase") AS "Lipase",
		MAX("Amylase") AS "Amylase",
		MAX("CPK") AS "CPK",
		MAX("CPK-MB") AS "CPK-MB",
		MAX("BNP") AS "BNP",
		MAX("PTT") AS "PTT",
		MAX("PTT_Ratio") AS "PTT_Ratio",
		MAX("Fe") AS "Fe",
		MAX("TIBC") AS "TIBC",
		MAX("Fe/TIBC Ratio") AS "Fe/TIBC Ratio",
		MAX("Serum_Osmolality") AS "Serum_Osmolality",
		MAX("TSH") AS "TSH",
		MAX("T3") AS "T3",
		MAX("T4") AS "T4",
		MAX("Free T4") AS "Free T4",
		MAX("Ionized Calcium") AS "Ionized Calcium",
		MAX("Triglycerides") AS "Triglycerides",
		MAX("Cortisol") AS "Cortisol",
		MAX("Uric Acid") AS "Uric Acid",
		MAX("Ammonia") AS "Ammonia",
		MAX("Vitamin B12") AS "Vitamin B12"
	FROM
		target2
	GROUP BY
		stay_id, date, "avg PC mode", gender, race
)
-- 加入SOFA
, target4 AS
(
	SELECT
		target3.stay_id,
		target3.date,
		"avg SaO2",
		"avg Respiration",
		"avg Heart Rate",
		"avg Systemic Systolic",
		"avg Systemic Diastolic",
		"avg Systemic Mean",
		"avg Compliance",
		"avg FiO2",
		"avg Minute Ventilation",
		"avg Mean Airway Pressure",
		"avg Peak Airway Pressure",
		"avg PEEP",
		"avg PC mode",
		"avg Pressure Support",
		"avg Plateau",
		"avg Tidal Volume",
		"avg Respiratory Rate",
		"avg ROXindex",
		"avg RASS",
		"avg Platelets x1000",
		"avg WBC x1000",
		"avg Hgb",
		"avg Albumin",
		"avg Total Protein",
		"avg Total Bilirubin",
		"avg PO2",
		"avg PaCO2",
		"avg Glucose",
		"avg BUN",
		"avg pH",
		"avg Sodium",
		"avg Potassium",
		"avg Magnesium",
		"avg Calcium",
		"avg Chloride",
		"avg creatinine",
		"avg HCO3",
		"avg Phosphate",
		"avg Alkaline Phos.",
		"avg AST (SGOT)",
		"avg ALT (SGPT)",
		"avg PT-INR",
		"Vasopressor",
		"Relaxant",
		"Sedation",
		"PPI",
		"Pain control",
		"total",
		"total2",
		"Fluid_intake_value",
		"Nutrition_Enteral_value",
		"Urine_value",
		"Aspergillus",
		"Candida",
		"Abdomen",
		"Blood",
		"Respiratory tract",
		"Skin and soft tissue",
		"Urinary tract",
		"Others",
		dod,
		dod_3day,
		dod_7day,
		dod_30day,
		dod_60day,
		dod_90day,
		"InvasiveVent",
		"tracheostomy",
		"NonInvasiveVent",
		"SupplementalOxygen",
		"HFNC",
		----------DNR相關-------------
		"Anxiety",
		"Assess for anxiety, depression, or delirium which may contribut",
		"Asystole",
		"Blood Transfusion",
		"Consult to pastoral care, social services, palliative care, psy",
		"DNAR (Do Not Attempt Resuscitation) [DNR]",
		"DNAR (Do Not Attempt Resuscitation) [DNR] / DNI",
		"DNI (do not intubate)",
		"DNR (do not resuscitate)",
		"DNR / DNI",
		"Early mobilization",
		"Encourage family to participate in care",
		"Encourage patient / family members to accept individual reponse",
		"Encourage patient / family to set and verbalize care goals",
		"Enlist family support / family sitters",
		"Explanation",
		"Family at bedside",
		"Family Called",
		"Family Conference",
		"Family Member",
		"Family Talked to MD",
		"Family Talked to RN",
		"Family Visited",
		"Full code",
		"Full resistance",
		"Fully awake",
		"Listen attentively when patient attempts to communicate",
		"Liver Failure",
		"Manage environment for patient''s maximum comfort",
		"Maintain GCS >= 8",
		"No Proxy",
		"No, not sedated",
		"Palliative Care",
		"Patient / family involved in treatment plan",
		"Patient / family will have adequate support once CMO decision h",
		"Patient / family will have support throughout the dying process",
		"Patient / family will participate in planning and initiating cu",
		"Patient refused",
		"Patient Verbalized",
		"Promote early mobility",
		"Rehab",
		"Rehabilitation",
		"SBT",
		"Social Service Involved",
		"Social Services",
		"Social Work",
		"Spiritual",
		"Spouse",
		"Thermoregulation",
		"TPN",
		"Tracheostomy",
		"Tracheostomy tube",
		"With family",
		"With spouse",
		"Withdraws",
		---抗生素---
		antibiotic,
		---SOFA---
		respiration,
		coagulation,
		liver,
		cardiovascular,
		cns,
		renal,
		sofa,
		----------------------------
		gender,
		age,
		race,
		dnr,
		apsiii,
		"MI",
		"CHF",
		"PVD",
		"CVD",
		"Dementia",
		"CPD",
		"RD",
		"PUD",
		"MLD",
		"DM_acute",
		"DM_Chronic",
		"Hemiplegia",
		"Renal",
		"Malignancy",
		"LD",
		"MST",
		"AIDS",
		"Troponin - I",
		"Troponin - T",
		"Ferritin",
		"Transferrin",
		"CRP",
		"Fibrinogen",
		"HDL",
		"LDL",
		"Total Cholesterol",
		"Direct Bilirubin",
		"Lactate",
		"LDH",
		"Lipase",
		"Amylase",
		"CPK",
		"CPK-MB",
		"BNP",
		"PTT",
		"PTT_Ratio",
		"Fe",
		"TIBC",
		"Fe/TIBC Ratio",
		"Serum_Osmolality",
		"TSH",
		"T3",
		"T4",
		"Free T4",
		"Ionized Calcium",
		"Triglycerides",
		"Cortisol",
		"Uric Acid",
		"Ammonia",
		"Vitamin B12"
	FROM 
		target3
	LEFT JOIN 
		mimiciv_derived.sofa_date as sofa
	ON 
		target3.stay_id = sofa.stay_id AND target3.date = sofa.date
)
-- 加入strength那些 (DNR_table2)
, target5 AS
(
	SELECT
		target4.stay_id,
		target4.date,
		"avg SaO2",
		"avg Respiration",
		"avg Heart Rate",
		"avg Systemic Systolic",
		"avg Systemic Diastolic",
		"avg Systemic Mean",
		"avg Compliance",
		"avg FiO2",
		"avg Minute Ventilation",
		"avg Mean Airway Pressure",
		"avg Peak Airway Pressure",
		"avg PEEP",
		"avg PC mode",
		"avg Pressure Support",
		"avg Plateau",
		"avg Tidal Volume",
		"avg Respiratory Rate",
		"avg ROXindex",
		"avg RASS",
		"avg Platelets x1000",
		"avg WBC x1000",
		"avg Hgb",
		"avg Albumin",
		"avg Total Protein",
		"avg Total Bilirubin",
		"avg PO2",
		"avg PaCO2",
		"avg Glucose",
		"avg BUN",
		"avg pH",
		"avg Sodium",
		"avg Potassium",
		"avg Magnesium",
		"avg Calcium",
		"avg Chloride",
		"avg creatinine",
		"avg HCO3",
		"avg Phosphate",
		"avg Alkaline Phos.",
		"avg AST (SGOT)",
		"avg ALT (SGPT)",
		"avg PT-INR",
		"Vasopressor",
		"Relaxant",
		"Sedation",
		"PPI",
		"Pain control",
		"total",
		"total2",
		"Fluid_intake_value",
		"Nutrition_Enteral_value",
		"Urine_value",
		"Aspergillus",
		"Candida",
		"Abdomen",
		"Blood",
		"Respiratory tract",
		"Skin and soft tissue",
		"Urinary tract",
		"Others",
		dod,
		dod_3day,
		dod_7day,
		dod_30day,
		dod_60day,
		dod_90day,
		"InvasiveVent",
		"tracheostomy",
		"NonInvasiveVent",
		"SupplementalOxygen",
		"HFNC",
		----------DNR相關-------------
		"Anxiety",
		"Assess for anxiety, depression, or delirium which may contribut",
		"Asystole",
		"Blood Transfusion",
		"Consult to pastoral care, social services, palliative care, psy",
		"DNAR (Do Not Attempt Resuscitation) [DNR]",
		"DNAR (Do Not Attempt Resuscitation) [DNR] / DNI",
		"DNI (do not intubate)",
		"DNR (do not resuscitate)",
		"DNR / DNI",
		"Early mobilization",
		"Encourage family to participate in care",
		"Encourage patient / family members to accept individual reponse",
		"Encourage patient / family to set and verbalize care goals",
		"Enlist family support / family sitters",
		"Explanation",
		"Family at bedside",
		"Family Called",
		"Family Conference",
		"Family Member",
		"Family Talked to MD",
		"Family Talked to RN",
		"Family Visited",
		"Full code",
		"Full resistance",
		"Fully awake",
		"Listen attentively when patient attempts to communicate",
		"Liver Failure",
		"Manage environment for patient''s maximum comfort",
		"Maintain GCS >= 8",
		"No Proxy",
		"No, not sedated",
		"Palliative Care",
		"Patient / family involved in treatment plan",
		"Patient / family will have adequate support once CMO decision h",
		"Patient / family will have support throughout the dying process",
		"Patient / family will participate in planning and initiating cu",
		"Patient refused",
		"Patient Verbalized",
		"Promote early mobility",
		"Rehab",
		"Rehabilitation",
		"SBT",
		"Social Service Involved",
		"Social Services",
		"Social Work",
		"Spiritual",
		"Spouse",
		"Thermoregulation",
		"TPN",
		"Tracheostomy",
		"Tracheostomy tube",
		"With family",
		"With spouse",
		"Withdraws",
		"Strength L Arm",
		"Strength L Leg",
		"Strength R Arm",
		"Strength R Leg",
		"Response",
		"Coping/Knowledge Deficit  NCP - Expected outcomes",
		---抗生素---
		antibiotic,
		---SOFA---
		respiration,
		coagulation,
		liver,
		cardiovascular,
		cns,
		renal,
		sofa,
		----------------------------
		gender,
		age,
		race,
		dnr,
		apsiii,
		"MI",
		"CHF",
		"PVD",
		"CVD",
		"Dementia",
		"CPD",
		"RD",
		"PUD",
		"MLD",
		"DM_acute",
		"DM_Chronic",
		"Hemiplegia",
		"Renal",
		"Malignancy",
		"LD",
		"MST",
		"AIDS",
		"Troponin - I",
		"Troponin - T",
		"Ferritin",
		"Transferrin",
		"CRP",
		"Fibrinogen",
		"HDL",
		"LDL",
		"Total Cholesterol",
		"Direct Bilirubin",
		"Lactate",
		"LDH",
		"Lipase",
		"Amylase",
		"CPK",
		"CPK-MB",
		"BNP",
		"PTT",
		"PTT_Ratio",
		"Fe",
		"TIBC",
		"Fe/TIBC Ratio",
		"Serum_Osmolality",
		"TSH",
		"T3",
		"T4",
		"Free T4",
		"Ionized Calcium",
		"Triglycerides",
		"Cortisol",
		"Uric Acid",
		"Ammonia",
		"Vitamin B12"
	FROM 
		target4
	LEFT JOIN 
		pj_dnr.DNR_table2 as DNR_table2
	ON 
		target4.stay_id = DNR_table2.stay_id AND target4.date = DNR_table2.date
)
-- 加入洗腎
, target6 AS
(
	SELECT
		target5.stay_id,
		target5.date,
		"avg SaO2",
		"avg Respiration",
		"avg Heart Rate",
		"avg Systemic Systolic",
		"avg Systemic Diastolic",
		"avg Systemic Mean",
		"avg Compliance",
		"avg FiO2",
		"avg Minute Ventilation",
		"avg Mean Airway Pressure",
		"avg Peak Airway Pressure",
		"avg PEEP",
		"avg PC mode",
		"avg Pressure Support",
		"avg Plateau",
		"avg Tidal Volume",
		"avg Respiratory Rate",
		"avg ROXindex",
		"avg RASS",
		"avg Platelets x1000",
		"avg WBC x1000",
		"avg Hgb",
		"avg Albumin",
		"avg Total Protein",
		"avg Total Bilirubin",
		"avg PO2",
		"avg PaCO2",
		"avg Glucose",
		"avg BUN",
		"avg pH",
		"avg Sodium",
		"avg Potassium",
		"avg Magnesium",
		"avg Calcium",
		"avg Chloride",
		"avg creatinine",
		"avg HCO3",
		"avg Phosphate",
		"avg Alkaline Phos.",
		"avg AST (SGOT)",
		"avg ALT (SGPT)",
		"avg PT-INR",
		"Vasopressor",
		"Relaxant",
		"Sedation",
		"PPI",
		"Pain control",
		"total",
		"total2",
		"Fluid_intake_value",
		"Nutrition_Enteral_value",
		"Urine_value",
		"Aspergillus",
		"Candida",
		"Abdomen",
		"Blood",
		"Respiratory tract",
		"Skin and soft tissue",
		"Urinary tract",
		"Others",
		dod,
		dod_3day,
		dod_7day,
		dod_30day,
		dod_60day,
		dod_90day,
		"InvasiveVent",
		"tracheostomy",
		"NonInvasiveVent",
		"SupplementalOxygen",
		"HFNC",
		----------DNR相關-------------
		"Anxiety",
		"Assess for anxiety, depression, or delirium which may contribut",
		"Asystole",
		"Blood Transfusion",
		"Consult to pastoral care, social services, palliative care, psy",
		"DNAR (Do Not Attempt Resuscitation) [DNR]",
		"DNAR (Do Not Attempt Resuscitation) [DNR] / DNI",
		"DNI (do not intubate)",
		"DNR (do not resuscitate)",
		"DNR / DNI",
		"Early mobilization",
		"Encourage family to participate in care",
		"Encourage patient / family members to accept individual reponse",
		"Encourage patient / family to set and verbalize care goals",
		"Enlist family support / family sitters",
		"Explanation",
		"Family at bedside",
		"Family Called",
		"Family Conference",
		"Family Member",
		"Family Talked to MD",
		"Family Talked to RN",
		"Family Visited",
		"Full code",
		"Full resistance",
		"Fully awake",
		"Listen attentively when patient attempts to communicate",
		"Liver Failure",
		"Manage environment for patient''s maximum comfort",
		"Maintain GCS >= 8",
		"No Proxy",
		"No, not sedated",
		"Palliative Care",
		"Patient / family involved in treatment plan",
		"Patient / family will have adequate support once CMO decision h",
		"Patient / family will have support throughout the dying process",
		"Patient / family will participate in planning and initiating cu",
		"Patient refused",
		"Patient Verbalized",
		"Promote early mobility",
		"Rehab",
		"Rehabilitation",
		"SBT",
		"Social Service Involved",
		"Social Services",
		"Social Work",
		"Spiritual",
		"Spouse",
		"Thermoregulation",
		"TPN",
		"Tracheostomy",
		"Tracheostomy tube",
		"With family",
		"With spouse",
		"Withdraws",
		"Strength L Arm",
		"Strength L Leg",
		"Strength R Arm",
		"Strength R Leg",
		"Response",
		"Coping/Knowledge Deficit  NCP - Expected outcomes",
		---抗生素---
		antibiotic,
		---SOFA---
		respiration,
		coagulation,
		liver,
		cardiovascular,
		cns,
		renal,
		sofa,
		---洗腎---
		Case when dialysis_summary.dialysis = 1 then 1 else 0 end as dialysis,
		----------------------------
		gender,
		age,
		race,
		dnr,
		apsiii,
		"MI",
		"CHF",
		"PVD",
		"CVD",
		"Dementia",
		"CPD",
		"RD",
		"PUD",
		"MLD",
		"DM_acute",
		"DM_Chronic",
		"Hemiplegia",
		"Renal",
		"Malignancy",
		"LD",
		"MST",
		"AIDS",
		"Troponin - I",
		"Troponin - T",
		"Ferritin",
		"Transferrin",
		"CRP",
		"Fibrinogen",
		"HDL",
		"LDL",
		"Total Cholesterol",
		"Direct Bilirubin",
		"Lactate",
		"LDH",
		"Lipase",
		"Amylase",
		"CPK",
		"CPK-MB",
		"BNP",
		"PTT",
		"PTT_Ratio",
		"Fe",
		"TIBC",
		"Fe/TIBC Ratio",
		"Serum_Osmolality",
		"TSH",
		"T3",
		"T4",
		"Free T4",
		"Ionized Calcium",
		"Triglycerides",
		"Cortisol",
		"Uric Acid",
		"Ammonia",
		"Vitamin B12"
	FROM 
		target5
	LEFT JOIN 
		mimiciv_derived.dialysis_summary as dialysis_summary
	ON 
		target5.stay_id = dialysis_summary.stay_id AND target5.date = dialysis_summary.date
)

-- 加入ICU類別
, target7 AS
(
	SELECT
		target6.stay_id,
		date,
		"avg SaO2",
		"avg Respiration",
		"avg Heart Rate",
		"avg Systemic Systolic",
		"avg Systemic Diastolic",
		"avg Systemic Mean",
		"avg Compliance",
		"avg FiO2",
		"avg Minute Ventilation",
		"avg Mean Airway Pressure",
		"avg Peak Airway Pressure",
		"avg PEEP",
		"avg PC mode",
		"avg Pressure Support",
		"avg Plateau",
		"avg Tidal Volume",
		"avg Respiratory Rate",
		"avg ROXindex",
		"avg RASS",
		"avg Platelets x1000",
		"avg WBC x1000",
		"avg Hgb",
		"avg Albumin",
		"avg Total Protein",
		"avg Total Bilirubin",
		"avg PO2",
		"avg PaCO2",
		"avg Glucose",
		"avg BUN",
		"avg pH",
		"avg Sodium",
		"avg Potassium",
		"avg Magnesium",
		"avg Calcium",
		"avg Chloride",
		"avg creatinine",
		"avg HCO3",
		"avg Phosphate",
		"avg Alkaline Phos.",
		"avg AST (SGOT)",
		"avg ALT (SGPT)",
		"avg PT-INR",
		"Vasopressor",
		"Relaxant",
		"Sedation",
		"PPI",
		"Pain control",
		"total",
		"total2",
		"Fluid_intake_value",
		"Nutrition_Enteral_value",
		"Urine_value",
		"Aspergillus",
		"Candida",
		"Abdomen",
		"Blood",
		"Respiratory tract",
		"Skin and soft tissue",
		"Urinary tract",
		"Others",
		dod,
		dod_3day,
		dod_7day,
		dod_30day,
		dod_60day,
		dod_90day,
		"InvasiveVent",
		"tracheostomy",
		"NonInvasiveVent",
		"SupplementalOxygen",
		"HFNC",
		----------DNR相關-------------
		"Anxiety",
		"Assess for anxiety, depression, or delirium which may contribut",
		"Asystole",
		"Blood Transfusion",
		"Consult to pastoral care, social services, palliative care, psy",
		"DNAR (Do Not Attempt Resuscitation) [DNR]",
		"DNAR (Do Not Attempt Resuscitation) [DNR] / DNI",
		"DNI (do not intubate)",
		"DNR (do not resuscitate)",
		"DNR / DNI",
		"Early mobilization",
		"Encourage family to participate in care",
		"Encourage patient / family members to accept individual reponse",
		"Encourage patient / family to set and verbalize care goals",
		"Enlist family support / family sitters",
		"Explanation",
		"Family at bedside",
		"Family Called",
		"Family Conference",
		"Family Member",
		"Family Talked to MD",
		"Family Talked to RN",
		"Family Visited",
		"Full code",
		"Full resistance",
		"Fully awake",
		"Listen attentively when patient attempts to communicate",
		"Liver Failure",
		"Manage environment for patient''s maximum comfort",
		"Maintain GCS >= 8",
		"No Proxy",
		"No, not sedated",
		"Palliative Care",
		"Patient / family involved in treatment plan",
		"Patient / family will have adequate support once CMO decision h",
		"Patient / family will have support throughout the dying process",
		"Patient / family will participate in planning and initiating cu",
		"Patient refused",
		"Patient Verbalized",
		"Promote early mobility",
		"Rehab",
		"Rehabilitation",
		"SBT",
		"Social Service Involved",
		"Social Services",
		"Social Work",
		"Spiritual",
		"Spouse",
		"Thermoregulation",
		"TPN",
		"Tracheostomy",
		"Tracheostomy tube",
		"With family",
		"With spouse",
		"Withdraws",
		"Strength L Arm",
		"Strength L Leg",
		"Strength R Arm",
		"Strength R Leg",
		"Response",
		"Coping/Knowledge Deficit  NCP - Expected outcomes",
		---抗生素---
		antibiotic,
		---SOFA---
		respiration,
		coagulation,
		liver,
		cardiovascular,
		cns,
		renal,
		sofa,
		---洗腎---
		dialysis,
		--ICU類別--
		Case when icustays.first_careunit = 'Cardiac Vascular Intensive Care Unit (CVICU)' then 1 else 0 end as "CVICU",
		Case when icustays.first_careunit = 'Coronary Care Unit (CCU)' then 1 else 0 end as "CCU",
		Case when icustays.first_careunit = 'Medical Intensive Care Unit (MICU)' then 1 else 0 end as "MICU",
		Case when icustays.first_careunit = 'Medical/Surgical Intensive Care Unit (MICU/SICU)' then 1 else 0 end as "MICU/SICU",
		Case when icustays.first_careunit = 'Neuro Intermediate' then 1 else 0 end as "Neuro Intermediate",
		Case when icustays.first_careunit = 'Neuro Stepdown' then 1 else 0 end as "Neuro Stepdown",
		Case when icustays.first_careunit = 'Neuro Surgical Intensive Care Unit (Neuro SICU)' then 1 else 0 end as "Neuro SICU",
		Case when icustays.first_careunit = 'Surgical Intensive Care Unit (SICU)' then 1 else 0 end as "SICU",
		Case when icustays.first_careunit = 'Trauma SICU (TSICU)' then 1 else 0 end as "TSICU",
		----------------------------
		gender,
		age,
		race,
		dnr,
		apsiii,
		"MI",
		"CHF",
		"PVD",
		"CVD",
		"Dementia",
		"CPD",
		"RD",
		"PUD",
		"MLD",
		"DM_acute",
		"DM_Chronic",
		"Hemiplegia",
		"Renal",
		"Malignancy",
		"LD",
		"MST",
		"AIDS",
		"Troponin - I",
		"Troponin - T",
		"Ferritin",
		"Transferrin",
		"CRP",
		"Fibrinogen",
		"HDL",
		"LDL",
		"Total Cholesterol",
		"Direct Bilirubin",
		"Lactate",
		"LDH",
		"Lipase",
		"Amylase",
		"CPK",
		"CPK-MB",
		"BNP",
		"PTT",
		"PTT_Ratio",
		"Fe",
		"TIBC",
		"Fe/TIBC Ratio",
		"Serum_Osmolality",
		"TSH",
		"T3",
		"T4",
		"Free T4",
		"Ionized Calcium",
		"Triglycerides",
		"Cortisol",
		"Uric Acid",
		"Ammonia",
		"Vitamin B12"
	FROM 
		target6
	LEFT JOIN 
		mimiciv_icu.icustays as icustays
	ON 
		target6.stay_id = icustays.stay_id
)
-- 加入CPOT
, target8 AS
(
	SELECT
		target7.stay_id,
		target7.date,
		"avg SaO2",
		"avg Respiration",
		"avg Heart Rate",
		"avg Systemic Systolic",
		"avg Systemic Diastolic",
		"avg Systemic Mean",
		"avg Compliance",
		"avg FiO2",
		"avg Minute Ventilation",
		"avg Mean Airway Pressure",
		"avg Peak Airway Pressure",
		"avg PEEP",
		"avg PC mode",
		"avg Pressure Support",
		"avg Plateau",
		"avg Tidal Volume",
		"avg Respiratory Rate",
		"avg ROXindex",
		"avg RASS",
		"avg Platelets x1000",
		"avg WBC x1000",
		"avg Hgb",
		"avg Albumin",
		"avg Total Protein",
		"avg Total Bilirubin",
		"avg PO2",
		"avg PaCO2",
		"avg Glucose",
		"avg BUN",
		"avg pH",
		"avg Sodium",
		"avg Potassium",
		"avg Magnesium",
		"avg Calcium",
		"avg Chloride",
		"avg creatinine",
		"avg HCO3",
		"avg Phosphate",
		"avg Alkaline Phos.",
		"avg AST (SGOT)",
		"avg ALT (SGPT)",
		"avg PT-INR",
		"Vasopressor",
		"Relaxant",
		"Sedation",
		"PPI",
		"Pain control",
		"total",
		"total2",
		"Fluid_intake_value",
		"Nutrition_Enteral_value",
		"Urine_value",
		"Aspergillus",
		"Candida",
		"Abdomen",
		"Blood",
		"Respiratory tract",
		"Skin and soft tissue",
		"Urinary tract",
		"Others",
		dod,
		dod_3day,
		dod_7day,
		dod_30day,
		dod_60day,
		dod_90day,
		"InvasiveVent",
		"tracheostomy",
		"NonInvasiveVent",
		"SupplementalOxygen",
		"HFNC",
		----------DNR相關-------------
		"Anxiety",
		"Assess for anxiety, depression, or delirium which may contribut",
		"Asystole",
		"Blood Transfusion",
		"Consult to pastoral care, social services, palliative care, psy",
		"DNAR (Do Not Attempt Resuscitation) [DNR]",
		"DNAR (Do Not Attempt Resuscitation) [DNR] / DNI",
		"DNI (do not intubate)",
		"DNR (do not resuscitate)",
		"DNR / DNI",
		"Early mobilization",
		"Encourage family to participate in care",
		"Encourage patient / family members to accept individual reponse",
		"Encourage patient / family to set and verbalize care goals",
		"Enlist family support / family sitters",
		"Explanation",
		"Family at bedside",
		"Family Called",
		"Family Conference",
		"Family Member",
		"Family Talked to MD",
		"Family Talked to RN",
		"Family Visited",
		"Full code",
		"Full resistance",
		"Fully awake",
		"Listen attentively when patient attempts to communicate",
		"Liver Failure",
		"Manage environment for patient''s maximum comfort",
		"Maintain GCS >= 8",
		"No Proxy",
		"No, not sedated",
		"Palliative Care",
		"Patient / family involved in treatment plan",
		"Patient / family will have adequate support once CMO decision h",
		"Patient / family will have support throughout the dying process",
		"Patient / family will participate in planning and initiating cu",
		"Patient refused",
		"Patient Verbalized",
		--CPOT--
		COALESCE("Muscle", 0)  as "Muscle",
		COALESCE("Vocalization", 0)  as "Vocalization",
		COALESCE("Body Movements", 0)  as "Body Movements",
		COALESCE("Facial Expressions", 0)  as "Facial Expressions",
		COALESCE("CPOT(SUM)", 0)  as "CPOT(SUM)",
		--------
		"Promote early mobility",
		"Rehab",
		"Rehabilitation",
		"SBT",
		"Social Service Involved",
		"Social Services",
		"Social Work",
		"Spiritual",
		"Spouse",
		"Thermoregulation",
		"TPN",
		"Tracheostomy",
		"Tracheostomy tube",
		"With family",
		"With spouse",
		"Withdraws",
		"Strength L Arm",
		"Strength L Leg",
		"Strength R Arm",
		"Strength R Leg",
		"Response",
		"Coping/Knowledge Deficit  NCP - Expected outcomes",
		---抗生素---
		antibiotic,
		---SOFA---
		respiration,
		coagulation,
		liver,
		cardiovascular,
		cns,
		renal,
		sofa,
		
		---洗腎---
		dialysis,
		--ICU類別--
		"CVICU",
		"CCU",
		"MICU",
		"MICU/SICU",
		"Neuro Intermediate",
		"Neuro Stepdown",
		"Neuro SICU",
		"SICU",
		"TSICU",
		----------------------------
		gender,
		age,
		race,
		dnr,
		apsiii,
		"MI",
		"CHF",
		"PVD",
		"CVD",
		"Dementia",
		"CPD",
		"RD",
		"PUD",
		"MLD",
		"DM_acute",
		"DM_Chronic",
		"Hemiplegia",
		"Renal",
		"Malignancy",
		"LD",
		"MST",
		"AIDS",
		"Troponin - I",
		"Troponin - T",
		"Ferritin",
		"Transferrin",
		"CRP",
		"Fibrinogen",
		"HDL",
		"LDL",
		"Total Cholesterol",
		"Direct Bilirubin",
		"Lactate",
		"LDH",
		"Lipase",
		"Amylase",
		"CPK",
		"CPK-MB",
		"BNP",
		"PTT",
		"PTT_Ratio",
		"Fe",
		"TIBC",
		"Fe/TIBC Ratio",
		"Serum_Osmolality",
		"TSH",
		"T3",
		"T4",
		"Free T4",
		"Ionized Calcium",
		"Triglycerides",
		"Cortisol",
		"Uric Acid",
		"Ammonia",
		"Vitamin B12"
	FROM 
		target7
	LEFT JOIN 
		pj_dnr.cpot as cpot
	ON 
		target7.stay_id = cpot.stay_id and target7.date = cpot.date
)
select * from target8
order by stay_id,date